# tools/sync_agent_assets.py
# Where: repository tooling for AI-agent assets.
# What: Generates native instruction, command, and skill adapters from shared sources.
# Why: Keep Codex, Cursor, Claude Code, GitHub Copilot, and Gemini aligned without hand-copying.

from __future__ import annotations

import argparse
from pathlib import Path


GENERATED_NOTE = "Generated by tools/sync_agent_assets.py. Edit the shared source instead."
GENERATED_DYNAMIC_GLOBS = (
    ".claude/commands/*.md",
    ".cursor/commands/*.md",
    ".github/prompts/*.prompt.md",
    ".gemini/commands/*.toml",
    ".claude/skills/*/SKILL.md",
)
GENERATED_DYNAMIC_ROOTS = (
    ".claude/commands",
    ".cursor/commands",
    ".github/prompts",
    ".gemini/commands",
    ".claude/skills",
)


def _read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _to_bytes(text: str) -> bytes:
    return text.encode("utf-8")


def _strip_leading_html_comment(text: str) -> str:
    stripped = text.lstrip()
    if not stripped.startswith("<!--"):
        return text.strip() + "\n"
    end = stripped.find("-->")
    if end == -1:
        return text.strip() + "\n"
    return stripped[end + 3 :].lstrip().rstrip() + "\n"


def _markdown_header(path: str, what: str, why: str) -> str:
    return (
        "<!--\n"
        f"{path}\n"
        "Where: generated agent adapter.\n"
        f"What: {what}\n"
        f"Why: {why}\n"
        f"{GENERATED_NOTE}\n"
        "-->\n\n"
    )


def _toml_basic_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _toml_multiline(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    return f'"""\n{escaped.rstrip()}\n"""'


def _agent_instruction_adapters(root: Path) -> dict[Path, bytes]:
    body = _strip_leading_html_comment(_read_text(root / "AGENTS.md"))
    return {
        root
        / "CLAUDE.md": _to_bytes(
            _markdown_header(
                "CLAUDE.md",
                "Claude Code project memory mirrored from AGENTS.md.",
                "Claude Code reads CLAUDE.md as project memory.",
            )
            + body
        ),
        root
        / "GEMINI.md": _to_bytes(
            _markdown_header(
                "GEMINI.md",
                "Gemini CLI project context mirrored from AGENTS.md.",
                "Gemini CLI reads GEMINI.md as hierarchical memory.",
            )
            + body
        ),
        root
        / ".github"
        / "copilot-instructions.md": _to_bytes(
            _markdown_header(
                ".github/copilot-instructions.md",
                "GitHub Copilot repository instructions mirrored from AGENTS.md.",
                "Copilot reads this file as repository-wide custom instructions.",
            )
            + body
        ),
        root
        / ".cursor"
        / "rules"
        / "project-guidelines.mdc": _to_bytes(
            "---\n"
            "description: Shared project instructions mirrored from AGENTS.md.\n"
            "globs:\n"
            "alwaysApply: true\n"
            "---\n\n"
            + _markdown_header(
                ".cursor/rules/project-guidelines.mdc",
                "Cursor project rule mirrored from AGENTS.md.",
                "Cursor reads .cursor/rules/*.mdc as reusable project rules.",
            )
            + body
        ),
    }


def _command_body(source: Path) -> str:
    return _strip_leading_html_comment(_read_text(source))


def _command_adapters(root: Path) -> dict[Path, bytes]:
    outputs: dict[Path, bytes] = {}
    source_dir = root / ".agents" / "commands"
    for source in sorted(source_dir.glob("*.md")):
        name = source.stem
        body = _command_body(source)
        description = f"Shared repository command: {name}"

        outputs[root / ".claude" / "commands" / f"{name}.md"] = _to_bytes(
            _markdown_header(
                f".claude/commands/{name}.md",
                f"Claude Code command adapter for .agents/commands/{name}.md.",
                "Claude Code discovers project slash commands in .claude/commands.",
            )
            + body
            + "\nUser arguments from Claude Code, if any:\n$ARGUMENTS\n"
        )
        outputs[root / ".cursor" / "commands" / f"{name}.md"] = _to_bytes(
            _markdown_header(
                f".cursor/commands/{name}.md",
                f"Cursor command adapter for .agents/commands/{name}.md.",
                "Cursor discovers project commands in .cursor/commands.",
            )
            + body
            + "\nIf text is provided after the command name, treat it as the command scope.\n"
        )
        outputs[root / ".github" / "prompts" / f"{name}.prompt.md"] = _to_bytes(
            _markdown_header(
                f".github/prompts/{name}.prompt.md",
                f"GitHub Copilot prompt adapter for .agents/commands/{name}.md.",
                "Copilot discovers reusable prompt files in .github/prompts.",
            )
            + body
            + "\nUse selected files, chat context, and any prompt arguments as scope.\n"
        )
        gemini_prompt = body + "\nUser arguments from Gemini CLI, if any:\n{{args}}\n"
        outputs[root / ".gemini" / "commands" / f"{name}.toml"] = _to_bytes(
            f"# .gemini/commands/{name}.toml\n"
            "# Where: generated Gemini CLI command adapter.\n"
            f"# What: Gemini command adapter for .agents/commands/{name}.md.\n"
            "# Why: Gemini CLI discovers custom commands as TOML files.\n"
            f"# {GENERATED_NOTE}\n\n"
            f"description = {_toml_basic_string(description)}\n"
            f"prompt = {_toml_multiline(gemini_prompt)}\n"
        )
    return outputs


def _skill_adapters(root: Path) -> dict[Path, bytes]:
    outputs: dict[Path, bytes] = {}
    source_root = root / ".agents" / "skills"
    for skill_md in sorted(source_root.glob("*/SKILL.md")):
        skill_name = skill_md.parent.name
        outputs[root / ".claude" / "skills" / skill_name / "SKILL.md"] = skill_md.read_bytes()
    return outputs


def render_files(root: Path) -> dict[Path, bytes]:
    outputs: dict[Path, bytes] = {}
    outputs.update(_agent_instruction_adapters(root))
    outputs.update(_command_adapters(root))
    outputs.update(_skill_adapters(root))
    return outputs


def _generated_dynamic_files(root: Path) -> list[Path]:
    paths: set[Path] = set()
    for pattern in GENERATED_DYNAMIC_GLOBS:
        paths.update(root.glob(pattern))
    return sorted(paths)


def _stale_generated_files(root: Path, expected: dict[Path, bytes]) -> list[Path]:
    expected_paths = set(expected)
    return [path for path in _generated_dynamic_files(root) if path not in expected_paths]


def _remove_empty_generated_parents(root: Path, path: Path) -> None:
    dynamic_roots = [root / relative_root for relative_root in GENERATED_DYNAMIC_ROOTS]
    for stop_at in dynamic_roots:
        if path == stop_at or not path.is_relative_to(stop_at):
            continue

        current = path
        while current != stop_at:
            try:
                current.rmdir()
            except OSError:
                break
            current = current.parent
        return


def write_files(root: Path, *, prune: bool = False) -> tuple[list[Path], list[Path]]:
    written: list[Path] = []
    removed: list[Path] = []
    outputs = render_files(root)

    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.exists() and path.read_bytes() == content:
            continue
        path.write_bytes(content)
        written.append(path)

    if prune:
        for path in _stale_generated_files(root, outputs):
            path.unlink()
            removed.append(path)
            _remove_empty_generated_parents(root, path.parent)

    return written, removed


def check_files(root: Path, *, prune: bool = False) -> list[Path]:
    stale: list[Path] = []
    outputs = render_files(root)

    for path, content in outputs.items():
        if not path.exists() or path.read_bytes() != content:
            stale.append(path)
    if prune:
        stale.extend(_stale_generated_files(root, outputs))
    return stale


def main() -> int:
    parser = argparse.ArgumentParser(description="Sync generated AI-agent adapter files.")
    parser.add_argument("--check", action="store_true", help="Exit non-zero if generated files are stale.")
    parser.add_argument(
        "--prune",
        action="store_true",
        help="Include generated files whose shared sources no longer exist; remove them during sync.",
    )
    args = parser.parse_args()

    root = Path(__file__).resolve().parents[1]
    if args.check:
        stale = check_files(root, prune=args.prune)
        if stale:
            print("Stale generated agent files:")
            for path in stale:
                print(path.relative_to(root))
            return 1
        print("Generated agent files are up to date.")
        return 0

    written, removed = write_files(root, prune=args.prune)
    if not written and not removed:
        print("Generated agent files are already up to date.")
        return 0
    if written:
        print("Updated generated agent files:")
        for path in written:
            print(path.relative_to(root))
    if removed:
        print("Removed stale generated agent files:")
        for path in removed:
            print(path.relative_to(root))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
